services:
  drcecim-upload:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      # Variables b치sicas del contenedor
      - HOST=0.0.0.0
      - PORT=8501
      
      # Configuraci칩n de credenciales de Google Cloud
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/service-account.json
      
      # Configuraci칩n de base de datos para evitar timeouts
      - DB_CONNECTION_TIMEOUT=3600
      - DB_KEEPALIVES_IDLE=600
      - DB_KEEPALIVES_INTERVAL=30
      - DB_KEEPALIVES_COUNT=3
      - DB_MAX_RETRIES=3
    
    volumes:
      # Volumen para datos persistentes
      - drcecim_data:/app/data
      - drcecim_logs:/app/logs
      - drcecim_temp:/app/temp
      # Montar credenciales de Google Cloud si est치n disponibles localmente
      - ./credentials/service-account.json:/app/credentials/service-account.json:ro
      # Montar archivo de secrets de Streamlit
      - ./.streamlit/secrets.toml:/app/.streamlit/secrets.toml:ro
    
    env_file:
      - .env
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  drcecim_data:
    driver: local
  drcecim_logs:
    driver: local
  drcecim_temp:
    driver: local 