# =============================================================================
# CONFIGURACIÓN DE DEPLOYMENT PARA GOOGLE CLOUD FUNCTIONS
# =============================================================================

# Configuración básica de la función
function_name: "drcecim-process-document"
entry_point: "process_document"
runtime: "python312"
region: "us-central1"

# Configuración de recursos
memory: "1024Mi"
timeout: "540s"  # 9 minutos (máximo para Cloud Functions)
cpu: "1"

# Configuración de escalado
min_instances: 0
max_instances: 10
concurrency: 1  # Procesamiento de un documento a la vez

# Configuración de trigger
trigger:
  type: "http"
  allow_unauthenticated: true  # Cambiar a false para producción

# Variables de entorno que se deben configurar
environment_variables:
  OPENAI_API_KEY: "required"
  GCS_BUCKET_NAME: "required"
  GCS_CREDENTIALS_PATH: "optional"
  GCF_PROJECT_ID: "required"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  MAX_FILE_SIZE_MB: "50"
  CHUNK_SIZE: "250"
  CHUNK_OVERLAP: "50"
  EMBEDDING_MODEL: "text-embedding-3-small"
  TEMP_DIR: "/tmp/drcecim_processing"

# Configuración de red
vpc_connector: ""  # Dejar vacío para usar red pública
ingress_settings: "ALLOW_ALL"  # ALLOW_ALL, ALLOW_INTERNAL_ONLY, ALLOW_INTERNAL_AND_GCLB

# Configuración de seguridad
service_account: ""  # Usar service account por defecto o especificar uno

# Configuración de logging
log_severity: "INFO"
log_format: "json"

# Configuración de health check
health_check_path: "/health"

# Archivos a incluir en el deployment
source_files:
  - "main.py"
  - "requirements.txt"
  - "config/"
  - "services/"
  - "models/"
  - "utils/"

# Archivos a excluir del deployment  
exclude_files:
  - "*.pyc"
  - "__pycache__/"
  - ".git/"
  - "test/"
  - "docs/"
  - "README.md"
  - "*.md"
  - ".env"
  - "temp/"
  - "logs/" 