[server]
# Configuración del servidor
port = 8501
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = true

[browser]
# Configuración del navegador
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = true

[runner]
# Configuración del runner
magicEnabled = true
postScriptGC = true
fastReruns = true
enforceSerializableSessionState = false

[logger]
# Configuración de logging
level = "info"
messageFormat = "%(asctime)s %(message)s"

[client]
# Configuración del cliente
showErrorDetails = true

[theme]
# Configuración del tema
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif" 